#!/bin/bash

if [ ! -d tex ]; then
    mkdir tex
fi

LHSFILES=$(find . | grep \.lhs)

for f in $LHSFILES; do
    FILE=$(basename $f .lhs)
    lhs2TeX $f > tex/${FILE}.tex || exit 1
    cd tex
    pdflatex ${FILE}.tex || exit 1
done
rm *.aux *.log *.ptb
